#!/bin/csh -f
set path=(../xmlsql ../SQLlib $path)

setenv N `sql notsco 'SELECT COUNT(*) FROM tester'`
setenv M `sql notsco 'SELECT COUNT(*) FROM log WHERE ts<curdate()'`
setenv T `sql notsco 'SELECT COUNT(DISTINCT tester) FROM log WHERE tester IS NOT NULL AND ts<curdate()'`
setenv S `sql notsco 'SELECT SUM(count) FROM scorecard'`
setenv A `sql notsco 'SELECT COUNT(DISTINCT tester) FROM scorecard'`

if("$M" != 0) then
/var/www/NOTSCO/toot/toot --quiet - << END
The NOTSCO test server for One Touch Switching currently has $N registered CPs.

Yesterday there were $T active CPs testings, passing $M messages.

Test messages total $S messages for $A testers still testing in the last month.
-- 
The NOTSCO server is located at https://notsco.uk and is free to use for #TOTSCO development testing.
END
endif

/var/www/NOTSCO/SQLlib/sql notsco \
		'DELETE FROM auth WHERE expiry<NOW()'	\
		'DELETE FROM log WHERE ts<curdate()'	\
		'DELETE FROM sor WHERE created<date_sub(NOW(),interval 60 day)'	\
		'DELETE FROM tester WHERE lastlogin IS NULL AND emailed<date_sub(NOW(),interval 7 day) OR lastlogin IS NOT NULL AND lastlogin<date_sub(now(),interval 6 month)' \
		'DELETE FROM pending WHERE sent<date_sub(NOW(),interval 1 day)' \
		'DELETE FROM scorecard WHERE last<date_sub(NOW(),interval 30 day)' \

